version: '3.3'

services:

  mongo:
    image: mongo
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
